### ISSUE TITLE
Where is the string "Download Subtitles" and how do i translate it

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#103]
In VLC View menu it says "Download Subtitles" to use VLSub.
But where does this string come from and how do i translate it?
I can't seem to find it, so maybe it have been changes?

**Comment by scootergrisen** [comment]
I suggest changing "Download Subtitles" (in VLC View menu) to the name of the extesion "VLSub" if it have not already been done.

**Comment by exebetche** [comment]
Nowhere in this repository. That's something the Vlc team add when they included the extension to Vlc (to put something more meaningfull about the purpose of this extension).

**Comment by scootergrisen** [comment]
Thats confusing if the extension is called "Download Subtitles" in a freshly installled VLC in the menu.
But called VLSub if you install it from within VLC.
