### ISSUE TITLE
Switching language does not work without internet connection

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#104]
If you go to config and change then language, the language are downloaded from the internet it seems when hit press the save button.

So with no internet connection you can't change language or close the dialog with the save button.

**Comment by exebetche** [comment]
If don't have en internet connection you can put the "locale" folder of the repository in the extension working directory. But again, if you don't have na internet connection you will not be able to use this extension at all.

**Comment by scootergrisen** [comment]
Where are the translation downloaded to when i change language?
I can't seem to find it.

I want to test my improved translation, but the one downloaded from the internet is an older version.
