### ISSUE TITLE
Different names for languages

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#105]
It seems different names are used for the languages.
Some are english, some are not.
So which once are we supporte to use?

translations_avail = {
    eng = 'English',
    cze = 'Czech', 
    dan = 'Danish', 
    dut = 'Nederlands',
    fre = 'Français',
    ell = 'Greek',
    baq = 'Basque',
    pob = 'Brazilian Portuguese',
    por = 'Portuguese (Portugal)',
    rum = 'Romanian',
    slo = 'Slovak',
    spa = 'Spanish',
    swe = 'Swedish',
    ukr = 'Ukrainian',
    hun = 'Hungarian'
  },

**Comment by exebetche** [comment]
I just copy the list of language from opensubtiltes without thinking ti much about it but if you have a list of a proper list of language name you can send me a commit.

**Comment by scootergrisen** [comment]
Should the names be in english?
