### ISSUE TITLE
Suggest changing website link

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#106]
Go to VLC : Tools > Plugins & Extensions.

Go to Active extensions tab.

Double click VLSub.

The website link is "http://www.opensubtitles.org/".
I suggest changing it to "https://github.com/exebetche/vlsub"

**Comment by exebetche** [comment]
That link is there to fulfill a requirement of opensubtitles to provide a link to their website if we use their api instead of the website.

**Comment by scootergrisen** [comment]
Do they require that you place link to them in exactly that place inside the description of the extension?

Clearly the website link for the extensions should link a website about the extension.

There is link opensubtitles.org in "Show Help". Is that not good enough?

The other extensions links to the extension on addons.videolan.org or github.
