### ISSUE TITLE
A lot of version number mismatch

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#107]
VLC 2.2.1 includes VLsub extension version 0.9.13.

Go to VLC : View > Download Subtitles. Says 0.9 in the dialog title.

Search for "vlsub" in the VLC "Plugins & Extensions" dialog... In the list is says: Version 0.9.8

Install it and go to "Active Extensions" tab, the one i just installed says "VLsub 0.9.10".

**Comment by exebetche** [comment]
You should say that to the Vlc team, I'm not managing the serving providing the "Plugins & Extensions" service, only this repository.

**Comment by scootergrisen** [comment]
What about the dialog title that says VLSub 0.9.

In the code it says "VLSub 0.9", it dont know if that is used for the dialog title:

  conf = {
    url = "http://api.opensubtitles.org/xml-rpc",
    path = nil,
    userAgentHTTP = "VLSub",
    useragent = "VLSub 0.9",
    translations_avail = {},
    downloadBehaviours = nil,
    languages = languages
  },

**Comment by exebetche** [comment]
Yes this is the 0.9, this is a major version. I didn't want to obfuscate the menu with the minor version "0.9.13" which is too long.

**Comment by scootergrisen** [comment]
Maybe remove the version number from the dialog title and also remove it from the extension title in Plugins & Extensions dialog.

People can click the extension to show more info about it.
