### ISSUE TITLE
Suggest changes to Mac OS string

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#108]
I would prefer this string to say it is for Mac OS in the beginning so i know its not for Windows:

So instead of:
To start the extension click on View > VLSub or Vlc > Extensions > VLSub on Mac OS.

This:
To start the extension on Mac OS click on View > VLSub or Vlc > Extensions > VLSub.

Or:
Start VLSub on Mac OS: View > VLSub or Vlc > Extensions > VLSub.

Maybe "VLSub or Vlc" should just reflect what is it called in the latest version.

**Comment by exebetche** [comment]
You can manage this within the extension, only provide a title, you should ask the Vlc team about it.
