### ISSUE TITLE
vlsub/VLsub/VLSub

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#109]
I seen vlsub/VLsub/VLSub being written differently, different places, so i suggest going though them all and deciding when way should be the correct/official way.

**Comment by scootergrisen** [comment]
No comment?

**Comment by exebetche** [comment]
I'd prefer comment about something on improving the code or adding new useful functionalities. This is not a trademark who gives a shit if it takes 2 or 3 upper case letters?

**Comment by waldyrious** [comment]
:-1: @exebetche
