### ISSUE TITLE
Subtitles won't save

### ISSUE THREAD

**Issue by kteman974** [exebetche/vlsub#119]
Hi,
The subtitles doesn't save on the files where the movies are, so if a turn VLC before the end I have to download it again. 
Any solutions ?

**Comment by exebetche** [comment]
On Windows, the extension can't write on folder if the path contains a non ascii character (like "ã", "é" etc). So you should put your videos on a folder without such characters (like "/data/my_movies/one_good_movie/").
The only solution to fix this problem would be to patch the lua runtime in Vlc. I proposed a patch to the Vlc team a long time ago but this never has been fixed:
https://trac.videolan.org/vlc/ticket/8131#comment:39

If the files aren't in a path with accentuated characters or if you're not using Windows, it is probably a wrong permission on the folder where your files are located.

**Comment by eskhool** [comment]
I am having the same problem on a mac without any special characters in the name. I am able to write to the folder where the file is as the same user that is running VLC. Any ideas?

**Comment by eskhool** [comment]
I should mention that I am playing the file from a network share but I am able to open the file from the Apple share and write any file in that folder so why shouldn't VLC/VLsub be able to do the same?

**Comment by patamunzo** [comment]
I have the same problem on a windows PC accessing a network drive shared from a linux box through samba, with only lowercase letters in the path and full permissions to everyone.
If I open the media file using the network name ( i.e. \\someshare\somefolder\file.mkv ) VLSub fails to save the .srt file in the same folder, and I have to do it manually.
If, on the other hand, I map the share or the folder to a drive letter (say, \\someshare\ mapped to X: so the opened file path becomes X:\somefolder\file.mkv) , VLSub works just fine.
I don't know if the mapping workaround is available on a mac though.

Hope this helps.

**Comment by exebetche** [comment]
Yes, it is known problem. Lua doesn't support Windows character encoding, only UTF8. I tried to push the VLC team to modify the lua embedded in VLC to support that but with no success at the time. Anyway you should report that to the VLC team.

**Comment by rbalogic** [comment]
Got the issue fixed from here - https://github.com/exebetche/vlsub/issues/213
