### ISSUE TITLE
Subtitles are downloaded in .gz file and VLSub cannot extract it

### ISSUE THREAD

**Issue by sergi-mm** [exebetche/vlsub#120]
With certain subtitles, they are downloaded in .gz compressed format, instead of .srt directly, and VLSub cannot extract them. The case is that these subtitles contains special characters like spanish Ñ...

Here the pastebin of debug output:
http://pastebin.com/ihxn0KQ6

Thansk for your work!

**Comment by sergi-mm** [comment]
Compressed .gz file is donwloaded with the name "Homeland 05x09 - The Litvinov Ruse (EspaÃ±ol (EspaÃ±a)).srt" and I think VLSub still search the filename with "Homeland 05x09 - The Litvinov Ruse (Español (España)).srt" ...

**Comment by jonathantribouharet** [comment]
I have the same problem and VLC freeze after that.
I have to unzip the file et rename it.

**Comment by exebetche** [comment]
Yes, it is known problem. Lua doesn't support Windows character encoding, only UTF8. I tried to push the VLC team to modify the lua embedded in VLC to support that but with no success at the time. Anyway you should report that to the VLC team.
