### ISSUE TITLE
Extension doesn't open when opened second time OS X

### ISSUE THREAD

**Issue by jelen-dev** [exebetche/vlsub#121]
Hi, I am running VLC player v 2.2.1 VLSub v 0.9.13 and when I load extension 1st time (after quitting the VLC) it loads as expected but once I try to open it again it just doesn't load. 3rd attempt will load it again 4th doesn't 5th will load it again etc.. So it is always needed to load it twice to (I guess) force close the previous instance and then open new one. Seems like there is some problem with quitting the extension when it is closed by "close" button maybe? I am using OS X 10.11.1 but the problem was the same on 10.10 and previous versions of VLC and VLCSub extensions (I had like 2 OS X major updates, 2-3 VLC versions and 2-3 VLC Sub versions)

**Comment by jelen-dev** [comment]
Maybe it is related to this issue: https://github.com/exebetche/vlsub/issues/71

**Comment by sbornia** [comment]
This is also happening on my end. OSX 10.11.3, VLC 2.0.8, VLSub 0.9.13

**Comment by Aigrefin** [comment]
I tried on my OSX, and this fixes the bug : #131

**Comment by exebetche** [comment]
Should be fixed by PR #131
