### ISSUE TITLE
Can't change user interface language without internet connection

### ISSUE THREAD

**Issue by scootergrisen** [exebetche/vlsub#123]
VLSub 0.9.13 and VLC 2.2.1 and Debian Linux with GNOME:

Try disabling your internet connection and then start VLC and show config and try changing the language of the user interface and press save.

Nothing will happen without internet connection.

Language will not change.
Dialog will not close.
VLC will freeze if you select the View menu.

Enable internet connection and it seems that the language gets downloaded when you change language.

So languages should proferly be included with VLSub and not relay on internet connection later on to download the language.

**Comment by Aigrefin** [comment]
The freeze should be corrected with PR #132, but you won't get translations embedded with VLSub yet.

The problem was that vlc didn't notify the extension properly about connection failure, making it block on a function that should never have been reached.
