### ISSUE TITLE
Can't download subs when file contains special characters like 'á, é, ...'

### ISSUE THREAD

**Issue by aibars** [exebetche/vlsub#129]
I always try to download spanish subs, but when the file contains the word 'Español' or 'España' I get the following message and therefore the file cannot be decompressed:

As an example, I tried to download the spanish sub for this file. The output was:
VLC could not open the file "E:\Series\Shameless US 6x01 - I Only Miss Her When I’m Breathing (Español (España)).srt.gz" (Bad file descriptor).

Steps:

Open some movie.
Go To: View -> Download Subtitles
Press Search by Hash.
Select a file meeting the described condition, and press Download Selection.

**Comment by exebetche** [comment]
Yes, it is known problem. Lua doesn't support Windows character encoding, only UTF8. I tried to push the VLC team to modify the lua embedded in VLC to support taht but with no success at the time. Anyway you should report that tito the VLC team.

**Comment by aibars** [comment]
Yeah, I've already loaded a ticket to the VLC team six months ago. 
https://trac.videolan.org/vlc/ticket/16454
