### ISSUE TITLE
Server overload

### ISSUE THREAD

**Issue by Gilbertobal** [exebetche/vlsub#130]
Server are overloaded please fix it

**Comment by exebetche** [comment]
I'm not in charge of the opensubtitles servers, ask opensubtitles.org.

**Comment by Wizek** [comment]
@exebetche Could there be any way to get around the server overload issue? E.g. rehost some or all of the srt files? Use a caching/fallback/mirror server? Use IPFS?

**Comment by Wizek** [comment]
Or could it be that logging into OpenSubtitles also helps?
