### ISSUE TITLE
Doesnt download subtitles in shared folders in windows

### ISSUE THREAD

**Issue by bradbury9** [exebetche/vlsub#136]
Fist of all, great job doing a magnificent plugin :-)

OS: windows 10, tried long time ago in win7, same problem.
VLC: 2.2.4
Description: The default VLCSub that comes shipped in VLC 2.2.4 has a bug which does not download the subtitles in the folder the video resides if that folder is a shared folder. Tried several videos, no one allowed the donload. The Sub is shown but is not stored in the shared video folder, only in AppData folder.

Steps to reproduce:
1- Open VLC
2- Open video
3- Go to 'Download subtitles'
4- Search by name
5- Click on Download selection
6- Following message is shown:
Success: Subtitles loaded
Error: Unable to save subtitles

VLC lua debug info: http://pastebin.com/cEhWPeg3

**Comment by exebetche** [comment]
Hi and thank you very much :)

Did you try with the file from this repo instead?

**Comment by bradbury9** [comment]
Im new to LUA, and I dont find in github.com/exebetche/vlsub the .luac file. Which tool can I use to compile the .lua into a .luac I can test in my environment?

**Comment by exebetche** [comment]
To compile .lua to .luac you can use vlc with this command if I believe [this file](https://github.com/videolan/vlc/blob/master/share/lua/intf/luac.lua):
vlc -I luaintf --lua-intf --lua-config 'luac={input="vlsub.lua",output="vlsub.luac"}'

But you don't have to, you can just put vlsub.lua as is in ProgramFiles\VideoLAN\VLC\lua\extensions\, then after restarting vlc you should see "Vlsub" at the bottom of the menu "View".

**Comment by bradbury9** [comment]
Same behaviour, I did leave the lua file in the extensions folder

2016-09-11 16:50 GMT+02:00 exebetche <notifications@github.com>:

**Comment by arielsalvo** [comment]
Hi,

I've seen the same on my end but I noticed this only happens when loading the video using a file:// URI.
Did you try mapping your shared folder to a drive letter?

**Comment by bradbury9** [comment]
Indeed, the problem no longer happens if not using shared folders path
sintax and is workarounded mapping the shared folder. Long time ago
developed a VLC based control and found out similar missbehaviour with the
URL formating in VLC's activex when working with playlists. Made it
working, but I dont recall how I did it

BTW:
Same workaround works for "Search by hash" / "Search never finishes"
problem [1].

[1]: https://github.com/exebetche/vlsub/issues/118

2016-09-18 7:59 GMT+02:00 Ariel Salvo <notifications@github.com>:

**Comment by exebetche** [comment]
Yes the solution in this case is to mount a share folder as a virtual drive. The extension need a drive letter (ex: Z:\folder) to work.
