### ISSUE TITLE
Unable to calculate hash in some mkv files

### ISSUE THREAD

**Issue by pcampora** [exebetche/vlsub#140]
I got the following error in VLC:

lua debug: [VLSub] Video URI: file:///D:/REVISAR/COUCHPOTATO/SUBS/The%20Lord%20of%20the%20Rings/The%20Lord%20of%20the%20Rings%20The%20Two%20Towers.2002/The%20Lord%20of%20the%20Rings%20The%20Two%20Towers.mkv
lua debug: [VLSub] file info The Lord of the Rings The Two Towers The Lord of the Rings The Two Towers.mkv D:/REVISAR/COUCHPOTATO/SUBS/The Lord of the Rings/The Lord of the Rings The Two Towers.2002/ mkv true false The Lord of the Rings The Two Towers D:/REVISAR/COUCHPOTATO/SUBS/The Lord of the Rings/The Lord of the Rings The Two Towers.2002/The Lord of the Rings The Two Towers.mkv file 1454111486 1454111486 0 33206 1454148243 -837245845 file 0 file:///D:/REVISAR/COUCHPOTATO/SUBS/The%20Lord%20of%20the%20Rings/The%20Lord%20of%20the%20Rings%20The%20Two%20Towers.2002/The%20Lord%20of%20the%20Rings%20The%20Two%20Towers.mkv
lua debug: [VLSub] Read hash data from file
lua warning: Error while running script C:\Program Files (x86)\VideoLAN\VLC\lua\extensions\vlsub.lua, function (null)(): ...am Files (x86)\VideoLAN\VLC\lua\extensions\vlsub.lua:1582: attempt to perform arithmetic on a nil value

Fle´s size is 7,21 GB
Attached is the file's codec info and operating system´s info.
![codec info](https://cloud.githubusercontent.com/assets/22891007/19443264/96d75026-9462-11e6-8646-cbefa44f7fdf.jpg)
![system info](https://cloud.githubusercontent.com/assets/22891007/19443286/a3c09aa4-9462-11e6-872f-479f5fb37239.jpg)

**Comment by Rukko** [comment]
Same here.

```
lua debug: [VLSub] Read hash data from file
lua warning: Error while running script C:\Program Files (x86)\VideoLAN\VLC\lua\extensions\vlsub.lua, function (null)(): ...am Files (x86)\VideoLAN\VLC\lua\extensions\vlsub.lua:1613: attempt to perform arithmetic on a nil value
lua warning: Could not translate click
```

**Comment by exebetche** [comment]
Yes that's known issue, on a Windows lua can't access files bigger than 2Go, and the VLC team disabled the possibility to use plugins to overcome this limitation. So I guess we're stuck with that.
