### ISSUE TITLE
VLSub 0.10.0 still broken, supports only Transfer-encoding: chunked

### ISSUE THREAD

**Issue by opensubtitles** [exebetche/vlsub#155]
Hi

I debugged VLSub, it seems it is not backward compatible with "old" server settings. Try with entry in /etc/hosts:
`92.240.234.122  api.opensubtitles.org`
it is freezing. I come to conclusion, now it works only with Transfer-encoding: chunked - thats also why other users are reporting Downloading is not working, because, there is not present this header (Content-Length is there...)

download headers:
https://www.dropbox.com/s/s23xorhozp6kphl/Screenshot%202016-11-16%2010.43.04.png?dl=0

Fix: make it compatible with Transfer-encoding: chunked and without Transfer-encoding: chunked

**Comment by VelocityRa** [comment]
Such a ridiculously unmaintained repo... shame really.

**Comment by varjolintu** [comment]
I've sent a pull request that fixes the problem with HTTP 1.1. Let's hope it will be included to the main branch soon. More info here:
https://github.com/varjolintu/vlsub/tree/download_fix

**Comment by VelocityRa** [comment]
To @thinklinux who downvoted me: the fact that this is still an issue despite the solution beeing known for so long proves my point.

**Comment by nicolas-besnard** [comment]
@VelocityRa you are free to fork and make it work. Not everybody has the time to maintain open-source code.

**Comment by VelocityRa** [comment]
@nicolas-besnard There are 17 unmerged PRs. This is what I meant.
