### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by noqnio** [exebetche/vlsub#161]
Hey
When i click "Search by hash" the extension stops responding.
After waiting for a big amount of time, the subtitles list is populated, and when i click "Download subtitle", it stops responding again and takes a big amount of time.
I don't know if this is relevant, but console says "http access error: error: HTTP/1.1 522 Origin Connection Time-out" and "lua generic error: /"
Latest VLsub, vlc 2.2.4, no other plug ins

**Comment by mert-celen** [comment]
It's calculating in background for hash of the video. For some reason, developers decided to not use async task for the calculation so it freezes the extension.

**Comment by noqnio** [comment]
It didn't use to do that, and on top of that it also freezes when i click download subtitle, so it can't be only the hash computation time

**Comment by rubendibattista** [comment]
Same here. +1

**Comment by danielmcoelho** [comment]
+1

**Comment by noqnio** [comment]
On Debian stretch I upgraded VLC and everything is back to normal

**Comment by rubendibattista** [comment]
Still having the problem on Mac OSX and VLsub 10.2 (while not on Windows).
