### ISSUE TITLE
Error: code '401 Unauthorized' (200)

### ISSUE THREAD

**Issue by mabushey** [exebetche/vlsub#174]
I get this error when I click "Search by hash" or "Search by name".
vlc media player 2.2.4 Weatherwax (revision 2.2.3-37-g888b7e89)
vlsub commit dcb7eaae4837a7d

**Comment by fraimondo** [comment]
Same here. Same versions.

**Comment by juanbenitopr** [comment]
I have de same problem

**Comment by juanbenitopr** [comment]
That's working  right now! I think the developers limit the requests in the time of the high usage.

**Comment by marsjaninzmarsa** [comment]
1. Go to https://www.opensubtitles.org/pl/newuser
2. Register
3. Open extension, Show config and provide username and password
4. Get profit from higher API quotas.

**Comment by exebetche** [comment]
When they are overloaded and probably the target of ddos attack, OS serves only registered users. So follow the steps given by @marsjaninzmarsa. Nothing else can be done on the plugin side beside using logging.

**Comment by comesta** [comment]
Using VLC Player for years with satisfaction, those time when I click "Search by hash" or "Search by name", I get this error: Code 401 Unauthorized (200). Im sorry I couldn’t find the procedure allowing me to correct this Vlc error. Thank you for your help. Cordially

**Comment by HiroAgustin** [comment]
Same

**Comment by made4praise** [comment]
1. Go to https://www.opensubtitles.org/en/newuser
2. Register
3. Confirm Email and sign in
4. **Open VLC** -> **View**->**VLSub**->**Show config** and enter your username and password and click save.
5. Restart and It's done.

**Comment by ardarvin** [comment]
>>Open VLC -> View->VLSub->Show config

This step, i.e. clicking "show config" button does not open a window. If I try to reopen VLSub, VLC freezes up -- requiring a force quit.

OSX 10.11.6 (yes, old)
VLC 3.0.8
VLSub 0.11.0

**Comment by rehannali** [comment]
@ardarvin Install VLSub 0.9.0 from extensions and click show config. Here you can enter username and password then you can use both extension.

**Comment by comesta** [comment]
> @ardarvin Installez VLSub 0.9.0 à partir des extensions et cliquez sur show config. Ici, vous pouvez entrer le nom d'utilisateur et le mot de passe, puis vous pouvez utiliser les deux extensions.

I couldn't find the show config. It will be better if you give us the link leading directely to  VLSub 0.9.0 . I have been seraching this extension on Google but no way to find it. Thanks for your help

**Comment by raderade** [comment]
Signed in opensub , signed in vlc , das noting for me , stil error code poping .

**Comment by comesta** [comment]
To Mr made4praise...You are asking >" 1. Go to https://www.opensubtitles.org/en/newuser
> 2. Register-> 3. Confirm Email and sign in-> 4. **Open VLC** -> **View**->**VLSub**->**Show config** and enter your username and password and click save.
> 5. Restart and It's done.
My reply is : Yes I already have been enregistred for years. Then WHERE can I find  the solution needed or  VLSub 0.9.0 and its extensions as mentionned.  Tnx

**Comment by rehannali** [comment]
> > @ardarvin Installez VLSub 0.9.0 à partir des extensions et cliquez sur show config. Ici, vous pouvez entrer le nom d'utilisateur et le mot de passe, puis vous pouvez utiliser les deux extensions.
> 
> I couldn't find the show config. It will be better if you give us the link leading directely to VLSub 0.9.0 . I have been seraching this extension on Google but no way to find it. Thanks for your help

You can download it from VLC itself. Open addon manager in VLC and download VLSub extension. It will download 0.9.0

**Comment by AllAdIn2708** [comment]
@rehannali 

Where can i find the Addon manager in VLC?

**Comment by rehannali** [comment]
> @rehannali 
> 
> Where can i find the Addon manager in VLC?

I believe you'll find in dropdown menu at top click VLC if using MAC and similar in Windows

**Comment by AllAdIn2708** [comment]
@ rehannali

Which dropdown menu?
I'm not een expert with this, sorry..

**Comment by rehannali** [comment]
> @ rehannali
> 
> Which dropdown menu?
> I'm not een expert with this, sorry..

<img width="790" alt="image" src="https://user-images.githubusercontent.com/22426977/78800950-7f5cbb00-79d5-11ea-9b5a-2e033f462561.png">

You need to press find more online add-ons if you don't see VLSub like in pic.

This screenshot is from MAC so there is little bit different in Windows PC.

**Comment by imgustavo** [comment]
Thanks a lot! it worked

**Comment by Riciouszxc** [comment]
> > > @ardarvin Installez VLSub 0.9.0 à partir des extensions et cliquez sur show config. Ici, vous pouvez entrer le nom d'utilisateur et le mot de passe, puis vous pouvez utiliser les deux extensions.
> > 
> > 
> > I couldn't find the show config. It will be better if you give us the link leading directely to VLSub 0.9.0 . I have been seraching this extension on Google but no way to find it. Thanks for your help
> 
> You can download it from VLC itself. Open addon manager in VLC and download VLSub extension. It will download 0.9.0

thanks it worked

**Comment by koullis22** [comment]
i have the same error.
registered to opensubtitles as suggested ..saved in config but still the same error.

any other idea/fix?

**Comment by uncabrian** [comment]
Thank you marsjaninzmarsa , I followed your advice and created an account then signed in on (Show Config) under the VLsub.  Just open movie, scroll over to View the open VLsub and look for Show config at the bottom of VLsub box. Then log in. Now it works fine again. Check my screenshot. Make sure you are using the username and password from (Opensubtitles.org)

![Screenshot (1)](https://user-images.githubusercontent.com/38665318/79023167-9cb49500-7b4d-11ea-9a3f-b41e892c2a28.png)

**Comment by comesta** [comment]
I followed your advice and created an account then signed in on (Show Config) under the VLsub. 

> Merci marsjaninzmarsa, j'ai suivi vos conseils et créé un compte puis connecté (Show Config) sous le VLsub. Ouvrez simplement le film, faites défiler pour afficher le VLsub ouvert et recherchez Afficher la configuration au bas de la boîte de VLsub. Ensuite, connectez-vous. Maintenant, cela fonctionne à nouveau correctement. Vérifiez ma capture d'écran. Assurez-vous que vous utilisez le nom d'utilisateur et le mot de passe de (Opensubtitles.org)
> 
> ![Capture d'écran (1)](https://user-images.githubusercontent.com/38665318/79023167-9cb49500-7b4d-11ea-9a3f-b41e892c2a28.png)

to Mr Non Abari@ 
 I followed your advice and created an account then signed in on but I don't find where is the "Show Config"  under the VLsub you're talking about. Could you please add a screenshot in order to give the best demonstration. Thanks
.

**Comment by rasitayaz** [comment]
I'm having this issue although I signed up on Open Subtitles, confirmed my email, entered my username and password to 'VLsub -> Show config'. I am having this issue on a linux operation system. I didn't encounter with this error in Windows. Any suggestions?

**Comment by uncabrian** [comment]
Please make certain you are using the correct Password. You can't use the github password on VLSub.  Make sure you are using the username and password from (Opensubtitles.org). I also made this same mistake. I can't give any help with Linux system but I'm sure it probably works the same.

**Comment by uncabrian** [comment]
> I'm having this issue although I signed up on Open Subtitles, confirmed my email, entered my username and password to 'VLsub -> Show config'. I am having this issue on a linux operation system. I didn't encounter with this error in Windows. Any suggestions?

Please make certain you are using the correct Password. You can't use the github password on VLSub. Make sure you are using the username and password from (Opensubtitles.org). I also made this same mistake. I can't give any help with Linux system but I'm sure VLC probably works the same on either system.

**Comment by rasitayaz** [comment]
> Please make certain you are using the correct Password. You can't use the github password on VLSub. Make sure you are using the username and password from (Opensubtitles.org). I also made this same mistake. I can't give any help with Linux system but I'm sure it probably works the same.

I made sure that I'm using the correct password. It logs in to opensubtitles.org successfully. But however, I'm still getting the error. Is there any other situation that could cause this error?

**Comment by uncabrian** [comment]
I'm sorry, I don't h

> > Please make certain you are using the correct Password. You can't use the github password on VLSub. Make sure you are using the username and password from (Opensubtitles.org). I also made this same mistake. I can't give any help with Linux system but I'm sure it probably works the same.
> 
> I made sure that I'm using the correct password. It logs in to opensubtitles.org successfully. But however, I'm still getting the error. Is there any other situation that could cause this error?

I'm sorry, i don't have the answer you need. It may have something to do with how Linux works. Maybe you could ask this question in a Linux forum and see if others are having this problem. Someone there may have found a fix. The (Opensubtitles.org) password should have fixed the problem. I know it did on Windows system and that's why I think a Linux Forum may have the answer you need. Or possibly going directly to VLC with this question could help you. You also may want to check the VLC site to see if you installed the correct version. I see they several versions listed for Linux systems. Good luck.

**Comment by rasitayaz** [comment]
> I'm having this issue although I signed up on Open Subtitles, confirmed my email, entered my username and password to 'VLsub -> Show config'. I am having this issue on a linux operation system. I didn't encounter with this error in Windows. Any suggestions?

I tried several different versions and I encountered different problems/bugs with each of them. But finally I found a version which works perfectly fine in official VLC repository. I downloaded this exact version of the VLC and copied /share/lua/extensions/VLSub.lua file to my extensions folder:

https://github.com/videolan/vlc/releases/tag/4.0-dev

This one is working fine for me and I hope it works for others who have the same problem as well.

**Comment by sequielo** [comment]
I have recenty upgraded Linux Mint from 19.3 to 20.
VLC VLSub plugin complained raising _401 error_, although I had provided a working username and password.

From here: https://www.reddit.com/r/VLC/comments/fyb58n/vlsub_error_401/

**I switched to English language, tried searching, and then switched back to Spanish AND IT WORKED!**

(Context: VLC version: 3.0.9.2, VLSub version 0.11.1)

**Comment by amithiel** [comment]
> I have recenty upgraded Linux Mint from 19.3 to 20.
> VLC VLSub plugin complained raising _401 error_, although I had provided a working username and password.
> 
> From here: https://www.reddit.com/r/VLC/comments/fyb58n/vlsub_error_401/
> 
> **I switched to English language, tried searching, and then switched back to Spanish AND IT WORKED!**
> 
> (Context: VLC version: 3.0.9.2, VLSub version 0.11.1)

Hi! i'm using this method on several linux distributions ( ubuntu, manjaro, pop_os etc..)
in my case, i want Portuguese subtitles (or brazilian). So, i need to change to english, search, and then go back to portuguese and search again.
When searching directly Portuguese, it displays the code 401 error.
I'm sorry to say guys, but in my opinion...this bug is here to stay,,,for years and years to come. Mark my words
(i hope i'm wrong, though)

**Comment by waleedrana777** [comment]
I am still having issues even when i am logged in with config.

**Comment by chinchillas** [comment]
This worked for me:
Go to opensubtitles.org and choose your preferred languages.
VLC: Input your user/password in VLSub0.9, close app
VLC: You'll find both versions of VLSub, choose 0.11.1 this time, then search hash or name.

**Comment by julian-alarcon** [comment]
> I have recenty upgraded Linux Mint from 19.3 to 20.
> VLC VLSub plugin complained raising _401 error_, although I had provided a working username and password.
> 
> From here: https://www.reddit.com/r/VLC/comments/fyb58n/vlsub_error_401/
> 
> **I switched to English language, tried searching, and then switched back to Spanish AND IT WORKED!**
> 
> (Context: VLC version: 3.0.9.2, VLSub version 0.11.1)

I found the same solution, but it's a PITA. Thank you @sequielo !

**Comment by mavosaure** [comment]
> I have recenty upgraded Linux Mint from 19.3 to 20. VLC VLSub plugin complained raising _401 error_, although I had provided a working username and password.
> 
> From here: https://www.reddit.com/r/VLC/comments/fyb58n/vlsub_error_401/
> 
> **I switched to English language, tried searching, and then switched back to Spanish AND IT WORKED!**
> 
> (Context: VLC version: 3.0.9.2, VLSub version 0.11.1)

Same problem, same workaround, using  VLC  3.0.9.2-1 on Xubuntu 20.04.
Thanks everybody!

**Comment by jannoke** [comment]
OpenSubtitles was hacked Aug 2021 and was kept under wraps. Data was leaked jan 2022. Around jan18 or so all passwords were wiped and you need to reset password and update vlsub config to get this working once again.

**Comment by rulatir** [comment]
> When they are overloaded and probably the target of ddos attack, OS serves only registered users. So follow the steps given by @marsjaninzmarsa. Nothing else can be done on the plugin side beside using logging.

Exactly how does the plugin get authorized as a result of me authenticating in the browser?
