### ISSUE TITLE
Extention not responding!

### ISSUE THREAD

**Issue by harrierbird** [exebetche/vlsub#183]
Hey there,

I get the following whenever I try to download a subtitle:

"Extention not responding!
 Extention 'VLsub 0.10.0' does not respond.
 Do you want to kill it now?

The only way out of this dialog box is by clicking "Yes". I don't get an error log after this. VLC just continues working after the extention is killed. Can anyone help? I can search for the subtitles file, either by hash or by name, it's only when I try to download them that this happens.

I'm on Mac OS Sierra.

Thank you for the help.

**Comment by ThatLurker** [comment]
Try using the latest version of vlsub from the [Release page](https://github.com/exebetche/vlsub/releases)

**Comment by harrierbird** [comment]
Thank you. Didn't realize there was a new one!
