### ISSUE TITLE
"Can't find suitable path to saveconfig, please set it manually" while entering username/password in 'Show Config' dialog

### ISSUE THREAD

**Issue by barreira** [exebetche/vlsub#184]
I couldn't download subtitles because of the problem described in #174.

So then I followed @marsjaninzmarsa suggestion to input my opensubtitles.org username and password in the 'Show Config' dialog, which didn't work because it outputs the error in the title of this issue (i.e. "Can't find suitable path to saveconfig, please set it manually").

I've also seen #25 and #32 which seemed to be similar problems (appeared on the search to solve my own problem) but to no avail.

**Edit**: the only thing I did differently than most users was that I installed VLC under C:\Program Files (x86)\VLC instead of C:\Program Files (x86)\VideoLAN\VLC which is the default option.

**Comment by exebetche** [comment]
These are not the same issues. The extension needs to write temporary files in a directory ad it doesn't work, maybe because the path contains accentuated character or an other reason. The path of the directory is indicated in Config > 'Vlsub working directory' and you can modify it here.

**Comment by barreira** [comment]
> maybe because the path contains accentuated character

My windows user folder does contain an accentuated character. That might be it.

>  The path of the directory is indicated in Config > 'Vlsub working directory' and you can modify it here.

Can you tell me what's the default one? Mine isn't showing anything.

**Comment by exebetche** [comment]
It doesn't matter, as long as the directory exists and the path doesn't contain any accentuated character.
You can create this one for example:
C:\Program Files (x86)\VLC\VLSUB

**Comment by barreira** [comment]
That doesn't help. I also checked and I wasn't using my windows user folder for anything VLC related and so there's no accentuated character.

In the image I annexed, you can see my 'Show Config' dialog settings. I had to manually insert the path to the VLSub folder (because clicking the blue link on the text only opens the file explorer and doesn't let me select the path to the folder) and yes, it exists and has no accentuated character. Yet, I still get the error message in the issue title.

![vlsub_prob2](https://user-images.githubusercontent.com/13606794/29687312-d021cb4e-8913-11e7-8d35-87dec38b7ced.PNG)

**Comment by exebetche** [comment]
Please join a pastebin of your debug log.
https://github.com/exebetche/vlsub/wiki/Troubleshooting

**Comment by barreira** [comment]
## **[FIXED]**

The problem was that the path `C:\Program Files (x86)\VLC\VLSub` I inserted - although it's the one windows gives if I right click on a folder in the file explorer (see the image below) - isn't the correct one because it comes in English (i.e. `Program Files (x86)`) instead of Portuguese (i.e. `Programas (x86)`) which is my OS language.

All I had to do was change that part of the path from English (`C:\Program Files (x86)\VLC\VLSub`) to Portuguese (`C:\Programas (x86)\VLC\VLSub`) and it worked.

I usually have all my programs and operating systems in English but this is not my computer.

![image](https://user-images.githubusercontent.com/13606794/29687681-3151b1da-8915-11e7-8982-03a4918c7706.png)

**Comment by exebetche** [comment]
Ok cool.
