### ISSUE TITLE
Why isn't the latest version (0.10.x) bundled with the new vlc 3.0?

### ISSUE THREAD

**Issue by pitsi** [exebetche/vlsub#199]
I upgraded to vlc 3.0 a few days ago and it still contains vlsub 0.9.x, which is broken. Why isn't the newer version of vlsub bundled with it? 
At first, I though that there had to be an update to vlc that will bring the new vlsub along, but vlc 2.2.5 was released after vlsub 0.10, however it still had 0.9 and so did the 3 newer releases of vlc 2.2.x (2.2.6 to 2.2.8). 
And now, there is a new major update of vlc to version 3, and it still has the broken vlsub 0.9.x. Why?

**Comment by djilll** [comment]
Because It,s a plugins third party and vlc 3.0.x doesnot include 7zip meanwhile sub are downloaded in compress format unzip them and drag them into vlc windows. It's not really nice to download the subs from the website that live on advertising... Might be why!

**Comment by pitsi** [comment]
I just noticed that vlc 3.0.2 bundles vlsub 0.11, so this issue can be closed.
However, it would be nice to know where the actual development of vlsub does happen.

**Comment by ThatLurker** [comment]
@pitsi it happens here and as we have not heard from @exebetche for a while and as he is not answering any issues here it's safe to say the development has stopped
