### ISSUE TITLE
VLC 3.0.1 with VLsub 0.10.2 Hangs on any search or download request

### ISSUE THREAD

**Issue by mdisante** [exebetche/vlsub#207]
This same issue has been happening now for over a year. I really appreciate that VLC and VLsub are available, but they are simply not usable. If this is a problem with server congestion, would it be overly difficult to have a message displayed like 'Server is busy, wait or retry?'.

**Comment by FrankRizzo890** [comment]
Yep, I have the same problem.

**Comment by sumanth-culli** [comment]
Even, I have the same problem.
I'm on Mac OS 10.13.3

**Comment by ThatLurker** [comment]
@duplex143  as your using a mac i would suggest moving to [iina](https://github.com/lhc70000/iina), it has internal sub downloader with multiple providers and the player itself is awesome and well maintained

**Comment by sumanth-culli** [comment]
Thanks for recommending [iina](https://lhc70000.github.io/iina/). Never heard of that until now. It's simply awesome.

**Comment by ionesculiviucristian** [comment]
Slow, buggy and outdated. Any news for the 3.x version of VLC?

**Comment by michalspondr** [comment]
After pressing Ctrl+M and analyzing debug output of VLC, I've seen this message after I tried to download subtitles:

lua debug: Clicking '/usr/lib64/vlc/lua/extensions/VLSub.luac': 'Download selection'
main debug: net: connecting to dl.opensubtitles.org port 80
main debug: connection succeeded (socket = 23)
lua debug: [VLsub] tmpFileName: /home/michal/.cache/vlc/Nanga Parbat.srt.gz
main debug: creating access: file:///home/michal/.cache/vlc/Nanga%20Parbat.srt.gz
main debug: (path: /home/michal/.cache/vlc/Nanga Parbat.srt.gz)
main debug: looking for access module matching "file": 20 candidates
main debug: using access module "filesystem"
main debug: looking for stream_filter module matching "prefetch,cache_read": 26 candidates
cache_read debug: Using stream method for AStream*
cache_read debug: starting pre-buffering
cache_read debug: received first data after 0 ms
cache_read debug: pre-buffering done 1024 bytes in 0s - 76923 KiB/s
main debug: using stream_filter module "cache_read"
main debug: looking for stream_filter module matching "any": 26 candidates
lua debug: Trying Lua scripts in /home/michal/.local/share/vlc/lua/playlist
lua debug: Trying Lua scripts in /usr/lib64/vlc/lua/playlist
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/anevia_streams.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/anevia_xml.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/appletrailers.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/bbc_co_uk.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/cue.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/dailymotion.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/jamendo.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/koreus.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/liveleak.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/newgrounds.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/rockbox_fm_presets.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/soundcloud.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/twitch.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/vimeo.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/vocaroo.luac
lua debug: Trying Lua playlist script /usr/lib64/vlc/lua/playlist/youtube.luac
lua debug: Trying Lua scripts in /usr/share/vlc/lua/playlist
main debug: no stream_filter modules matched
main debug: looking for stream_directory module matching "any": 0 candidates
main debug: no stream_directory modules
main debug: removing module "cache_read"
main debug: removing module "filesystem"
**lua warning: Error while running script /usr/lib64/vlc/lua/extensions/VLSub.luac, function (null)(): lua/extensions/VLSub.lua:1441: VLC lua error in file lua/libs/stream.c line 117 (function vlclua_directory_stream_new)**
lua warning: Could not translate click

VLC 3.0.4 @ Gentoo Linux
vlsub 0.11.0

**Comment by Wonko7** [comment]
same as  @michalspondr, vlc 3.0.7.1

**Comment by Wonko7** [comment]
@michalspondr : fixed by adding a bunch of useflags to vlc:
X a52 alsa aom archive bidi dav1d dbus dts dvbpsi dvd encode faad ffmpeg flac fontconfig gcrypt gme gstreamer jpeg libass libcaca libnotify libsamplerate live lua mad matroska mp3 mpeg musepack ncurses ogg omxil opencv opus png postproc pulseaudio qt5 shout ssl svg taglib theora tremor truetype twolame udev v4l vaapi vorbis vpx x264 x265 xml

**Comment by grount** [comment]
@Wonko7, please elaborate on how to solve the issue.

**Comment by mdisante** [comment]
I have found that with the latest version of VLC (3.0.8) and the latest version of Vlsub (0.11.0) everything works fine with the default settings. Once in a while, Vlsub will appear to hang due to a non-response from the web site it is referencing. If you wait it out (roughly a minute or so) it will come back and you can retry or gracefully exit Vlsub.

**Comment by Wonko7** [comment]
@grount it was a bug specific to those installing vlc from gentoo, the default minimal useflags aren't sufficient to get vlsub working.

**Comment by Nowa-Ammerlaan** [comment]
> @grount it was a bug specific to those installing vlc from gentoo, the default minimal useflags aren't sufficient to get vlsub working.

Which USE flag fixed the issue? I'm getting the same error when trying to download any subtitle.

**Comment by Nowa-Ammerlaan** [comment]
> > @grount it was a bug specific to those installing vlc from gentoo, the default minimal useflags aren't sufficient to get vlsub working.
> 
> Which USE flag fixed the issue? I'm getting the same error when trying to download any subtitle.

It's `USE=archive` that causes this error if it is disabled (and of course lua is also required).
