### ISSUE TITLE
Vlsub nolonger works on linux?

### ISSUE THREAD

**Issue by RavianXReaver** [exebetche/vlsub#208]
It was working fine 3-4 days ago and suddenly it stopped working. I dont understand why? I tried generating subs for both Movies/tvseries but none worked. Any1 else experiencing the same issue?

**Comment by aasutossh** [comment]
I thought It was just me, I reinstalled it about 20-30 times. As expected didn't work.

**Comment by Keammoort** [comment]
It doesn't seem to be Linux related. I can't get it to work on both Linux and Windows. I get 0 results for all the videos.

**Comment by aasutossh** [comment]
I get results but gets stuck at "downloading 100%" point.

**Comment by RavianXReaver** [comment]
The problem seems to be solved. I can view and download subs for TvSeries like before, but subs still cannot be downloaded for movies(existing issue)
