### ISSUE TITLE
Nobody improve this plugin? Is not possible add more website to download subtitles?

### ISSUE THREAD

**Issue by SoyDiego** [exebetche/vlsub#222]
It would be amazing to be able to update this plugin and make it work similar to BSPlayer by looking for plugins automatically when starting the video and being able to add some subtitle sites. I'm asking and dreaming a lot, right? :(
There is no other alternative?

**Comment by ThatLurker** [comment]
You could try to make updates to the vlc github https://github.com/videolan/vlc/tree/master/share/lua/extensions vlsub is also found there

**Comment by SoyDiego** [comment]
> You could try to make updates to the vlc github https://github.com/videolan/vlc/tree/master/share/lua/extensions vlsub is also found there

I'm a bad coder... :(
