### ISSUE TITLE
VlSub 0.11.0 [401 Unauthorized Issue]

### ISSUE THREAD

**Issue by shahidsabadia** [exebetche/vlsub#233]
Recently started facing "401 Unauthorized (200) "  as well as not responding issues, when searching a subtitle on VLSub 0.11.0. 

(I am using VLC Player 3.0.8]

Could you please help to get this fixed.
![Capture](https://user-images.githubusercontent.com/19795617/79127982-6cc0f800-7dc0-11ea-8a54-ef7742525122.JPG)
![Capture1](https://user-images.githubusercontent.com/19795617/79127987-6df22500-7dc0-11ea-8267-3972697dee32.JPG)

**Comment by shahidsabadia** [comment]
https://github.com/exebetche/vlsub/issues/227

This solved my issue ...

**Comment by assendk** [comment]
I just see randomly 401. After waiting 2-3 min and trying again everything is fine. Probably there is some server overload at the moment
