### ISSUE TITLE
Failed to generate hash

### ISSUE THREAD

**Issue by 2mg** [exebetche/vlsub#238]
VLC 3.0.11 Vetinari + VLSUB 0.11.1 + Win7x64.

Can't generate hash locally and via network for any videos.

**Comment by BennettBenson** [comment]
VLC 3.0.20 Vetinari + VLSUB 0.11.1 + Windows 11 Pro Version	23H2 OS build	22631.3447

This still an open issue. Can I get you any more info to help?

**Comment by 2mg** [comment]
It works now, thanks
