### ISSUE TITLE
[Workaround/Fix Identified] VLSub 0.11.1 Not Working Anymore. 

### ISSUE THREAD

**Issue by q5BWr6gN** [exebetche/vlsub#251]
Searching by name and attempting to download any subtitle now produces the following error: "Unable to save subtitles Click here to open the file".

I'm using VLC 3.0.18 Vetinari. 

Multiple users on the VLC subreddit are also reporting this problem.

**Comment by AllanHigdon** [comment]
I use VLC 3.0.19. Two days ago, I was seeing the same error message.
Since yesterday, VLSub 0.11.1 has been working for me.

**Comment by Neter56** [comment]
Same here, VLSub 0.11.1 is crashing on search attempt:  
![image](https://github.com/exebetche/vlsub/assets/19910837/0edf2b16-22ce-4d39-9f05-12df35b0fdd5)  

Using latest VLC v. 3.0.20

**Comment by Atalantia** [comment]
VLC 3.0.20 MacOS 10.15.6 Working good.

**Comment by q5BWr6gN** [comment]
I found a fix. If you go to this [repository](https://fossies.org/linux/misc/vlc-3.0.20.tar.xz/vlc-3.0.20/share/lua/extensions/VLSub.lua?m=b) and download this version instead, it seems to work. 

Go [here](https://fossies.org/linux/vlc/share/lua/extensions/VLSub.lua) if you want to read the source code before downloading.

**Comment by q5BWr6gN** [comment]
> Same here, VLSub 0.11.1 is crashing on search attempt: ![image](https://private-user-images.githubusercontent.com/19910837/282711843-0edf2b16-22ce-4d39-9f05-12df35b0fdd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzcwNjgsIm5iZiI6MTcwMjQzNjc2OCwicGF0aCI6Ii8xOTkxMDgzNy8yODI3MTE4NDMtMGVkZjJiMTYtMjJjZS00ZDM5LTlmMDUtMTJkZjM1YjBmZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAzMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MmY1OGFkMzdjYjRjYWQ0YWVmNzJjOGQyMTlhNzNhNmQ1NWI4MDMzMDhlMDljYTYzMzUxNTllZmM0NjM0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dy2bwmmRA1YDlsQLp2I9LuvaMp8ylbaUgyDwNYNlQvU)
> 
> Using latest VLC v. 3.0.20

You might be interested in this.

**Comment by napnapnapnap** [comment]
I created a repo for better visibility : https://github.com/napnapnapnap/vlsub
