### ISSUE TITLE
'VLsub 0.9.10 not responding' pop-ups for every functions

### ISSUE THREAD

**Issue by neitsab** [exebetche/vlsub#29]
Hello, I'm using VLC 2.0.8 (so as to avoid the bug #28), on Ubuntu GNOME Remix 12.10 x64.
The extension opens properly, but when I try to do a hash or a normal search, it hangs and then a pop-up appears saying "Extension not responding! Extension 'VLsub 0.9.10 ' does not respond. Do you want to kill it now?" with a progress bar stuck at 0%. Here's a screenshot :
![vlsub_not_responding](https://f.cloud.github.com/assets/2963014/1314278/9680506c-326f-11e3-970a-acd42452d30a.png)

If I wait 10-15 seconds, this window disappears and I get the results from the search. Same error message appears when I'm changing the settings. When I try to click "Close" to close the extension window, it doesn't work and I have to hit the cross in top-right corner. Then after the window"s already closed, the same "Extension not responding" window pops up, and hence I click "Yes" for killing it (even though no extension window is apparent anymore).

Tell me if you need more info. Nothing appears in VLC Message dialog (level 0), but it seems to be badly interacting with VLC itself, since opening VLC menus while the extension is hanging makes the whole program hangs.
Thanks a lot for your excellent extension, which provides a much needed feature in VLC.

**Comment by ClintEsteMadera** [comment]
for those having this problem in 2016, with vlsub v0.9.13 and VLC >= 2.2, I got this problem fixed after upgrading both VLC to the latest version (2.2.4) and vlsub to the latest version (0.10.0).
