### ISSUE TITLE
Error: File reading failed

### ISSUE THREAD

**Issue by pichanz** [exebetche/vlsub#51]
Hi,
I got a bug in vlsub 0.9.10.
i use VLC 2.0.8 x64 on Win8.1
the error is as follow:
File reading failed:
VLC could not open the file "Data\Media\Videos\Sherlock.3x03.HDTV_x264-FoV.srt.gz". (Bad file descriptor)

the subtitle is succesfully downloaded and it exists in the directory as a .gz archive by the name: Sherlock.3x03.HDTV_x264-FoV.srt.gz
but it seems like the subtitle is failed to be extracted from the .gz archive, because the srt file is created but it's empty (0 byte).

is this a new bug?
because i'd been using vlsub on my old pc and it runs without this bug.

Please help :)

Thanks!

**Comment by LeoFeriyDust** [comment]
Well i had the same problem. solution was just to tun of the sharing of the file/folder.... stupid windows :/
