### ISSUE TITLE
Hangs when close window in MacOSX

### ISSUE THREAD

**Issue by erseco** [exebetche/vlsub#71]
I'm using 0.9.12 in VLC 2.2 in MacOSX, i can search and download subtitles with no problems, but when I click to close the vlsub windows all VLC hangs, I need to force close and reopen (the subs was downloaded correctly

**Comment by consideRatio** [comment]
what xenio wrote just above this comment worked for me as well

**Comment by consideRatio** [comment]
ill test any ideas for you if you dont have a mac os to test on, subscribed to this thread so ill probably be quite quick to respond

**Comment by Aigrefin** [comment]
I tried on my OSX, and this fixes the bug : #131

**Comment by exebetche** [comment]
Should be fixed with PR #131
